# Generated by Django 2.1.15 on 2021-01-18 19:40

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=partial_date.fields.PartialDateField(blank=True, default=None, help_text='YYYY or YYYY-MM or YYYY-MM-DD', null=True),
        ),
    ]
