# Generated by Django 2.1.15 on 2021-01-19 04:58

from django.db import migrations
import djangoyearlessdate.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210119_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='year',
            field=djangoyearlessdate.models.YearField(blank=True, default=None, null=True),
        ),
    ]
