# Generated by Django 2.1.15 on 2021-01-18 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('Affiliation', models.CharField(max_length=256)),
                ('AreasOfInterest', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('EmailForVerification', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('homepage', models.URLField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='register.UserProfile'),
        ),
        migrations.AddField(
            model_name='coauthor',
            name='coAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthor', to='register.UserProfile'),
        ),
    ]
